repos:
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        args: [-s]
      - id: go-imports
      - id: golangci-lint
        args: [--fix]
      - id: go-unit-tests
      - id: go-mod-tidy

-   repo: local
    hooks:
      - id: go-build-test
        name: go build and test
        entry: bash -c 'go build ./... && go test ./...'
        language: system
        types: [go]
        pass_filenames: false
